/* Departamentos y municipios de Colombia (catálogo para combos de registro de finca). */
'use strict';

const DEPARTAMENTOS = {
  'Amazonas': ['Leticia', 'Puerto Nariño'],
  'Antioquia': ['Medellín', 'Abejorral', 'Andes', 'Apartadó', 'Bello', 'Caucasia', 'Chigorodó', 'Envigado', 'Itagüí', 'La Ceja', 'Marinilla', 'Rionegro', 'Santa Fe de Antioquia', 'Sonsón', 'Turbo', 'Urrao', 'Yarumal'],
  'Arauca': ['Arauca', 'Saravena', 'Tame'],
  'Atlántico': ['Barranquilla', 'Baranoa', 'Malambo', 'Puerto Colombia', 'Sabanalarga', 'Soledad'],
  'Bogotá D.C.': ['Bogotá'],
  'Bolívar': ['Cartagena', 'Carmen de Bolívar', 'Magangué', 'Mompox', 'San Juan Nepomuceno', 'Turbaco'],
  'Boyacá': ['Tunja', 'Chiquinquirá', 'Duitama', 'Garagoa', 'Moniquirá', 'Paipa', 'Puerto Boyacá', 'Sogamoso', 'Villa de Leyva'],
  'Caldas': ['Manizales', 'Aguadas', 'Anserma', 'Chinchiná', 'La Dorada', 'Neira', 'Riosucio', 'Salamina', 'Villamaría'],
  'Caquetá': ['Florencia', 'El Doncello', 'San Vicente del Caguán'],
  'Casanare': ['Yopal', 'Aguazul', 'Monterrey', 'Paz de Ariporo', 'Villanueva'],
  'Cauca': ['Popayán', 'El Tambo', 'Guapi', 'Miranda', 'Santander de Quilichao', 'Silvia', 'Timbío'],
  'Cesar': ['Valledupar', 'Aguachica', 'Bosconia', 'Chiriguaná', 'Curumaní'],
  'Chocó': ['Quibdó', 'Acandí', 'Istmina', 'Nuquí'],
  'Córdoba': ['Montería', 'Cereté', 'Chinú', 'Lorica', 'Montelíbano', 'Planeta Rica', 'Sahagún'],
  'Cundinamarca': ['Fusagasugá', 'Anapoima', 'Chía', 'Choachí', 'Facatativá', 'Girardot', 'La Mesa', 'Mosquera', 'Pacho', 'Soacha', 'Ubaté', 'Villeta', 'Zipaquirá'],
  'Guainía': ['Inírida'],
  'Guaviare': ['San José del Guaviare'],
  'Huila': ['Neiva', 'Garzón', 'Gigante', 'La Plata', 'Palermo', 'Pitalito', 'San Agustín', 'Timaná'],
  'La Guajira': ['Riohacha', 'Albania', 'Dibulla', 'Maicao', 'San Juan del Cesar', 'Uribia'],
  'Magdalena': ['Santa Marta', 'Ciénaga', 'El Banco', 'Fundación', 'Plato'],
  'Meta': ['Villavicencio', 'Acacías', 'Cumaral', 'Granada', 'Puerto López', 'Restrepo', 'San Martín'],
  'Nariño': ['Pasto', 'Ipiales', 'La Unión', 'Sandoná', 'Tumaco', 'Túquerres'],
  'Norte de Santander': ['Cúcuta', 'Chinácota', 'Los Patios', 'Ocaña', 'Pamplona', 'Villa del Rosario'],
  'Putumayo': ['Mocoa', 'Orito', 'Puerto Asís', 'Sibundoy', 'Valle del Guamuez'],
  'Quindío': ['Armenia', 'Buenavista', 'Calarcá', 'Circasia', 'Córdoba', 'Filandia', 'Génova', 'La Tebaida', 'Montenegro', 'Pijao', 'Quimbaya', 'Salento'],
  'Risaralda': ['Pereira', 'Apía', 'Belén de Umbría', 'Dosquebradas', 'La Virginia', 'Marsella', 'Mistrató', 'Santa Rosa de Cabal', 'Santuario'],
  'San Andrés y Providencia': ['San Andrés', 'Providencia'],
  'Santander': ['Bucaramanga', 'Barichara', 'Barrancabermeja', 'Floridablanca', 'Girón', 'Málaga', 'Piedecuesta', 'San Gil', 'San Vicente de Chucurí', 'Socorro', 'Vélez'],
  'Sucre': ['Sincelejo', 'Corozal', 'Ovejas', 'San Marcos', 'Sincé', 'Tolú'],
  'Tolima': ['Ibagué', 'Chaparral', 'El Espinal', 'Honda', 'Líbano', 'Mariquita', 'Melgar', 'Purificación', 'Rovira'],
  'Valle del Cauca': ['Cali', 'Buenaventura', 'Buga', 'Caicedonia', 'Cartago', 'El Cerrito', 'Jamundí', 'Palmira', 'Pradera', 'Roldanillo', 'Sevilla', 'Tuluá', 'Yumbo'],
  'Vaupés': ['Mitú'],
  'Vichada': ['Puerto Carreño'],
};
